name: Web App

on:
  push:
    branches:
      - webapp
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: olegtarasov/get-tag@v2 # that generate $GIT_TAG_NAME env
        id: tagName
        with:
          tagRegex: 'internal-v([0-9]+.[0-9]+.[0-9]+\+[0-9]+)' # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
          tagRegexGroup: 1 # Optional. Default is 1.
      - name: Replace YAML version with tag version
        run: |
          sed -i 's/99.99.99+99/'$GIT_TAG_NAME'/g' pubspec.yaml|
          echo "Tag used version:"$GIT_TAG_NAME
    
      - name: Build Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.0'
          channel: 'stable'
          
      - run: flutter pub get
      - run: flutter build web --release

      - name: Upload artifact for Github Release and Deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: build/web/
    
      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "."
          tag: v1.1.${{ github.run_number }}

    
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app
    
      - name: 'Deploy to Azure Web App'
        id: deploy-to-static-webapp
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "upload"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_PEBBLE_0256C6710 }}
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "/" # Built app content directory - optional
